framework:
    messenger:
        failure_transport: failed
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: '%env(FAILED_MESSENGER_TRANSPORT_DSN)%'

        routing:
            'Messenger\ToSynchronizer': async