monolog:
    channels:
        - deprecation

when@dev:
    monolog:
        handlers:
            main:
                level: debug
                type: stream
                channels: ["!event"]
                path: "%kernel.logs_dir%/%kernel.environment%.log"
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                handler: nested
                action_level: error
                channels: ["!event"]
                type: fingers_crossed
                excluded_http_codes: [404, 405]
            nested:
                level: debug
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"

when@prod:
    monolog:
        handlers:
            main:
                handler: nested
                buffer_size: 50
                action_level: error
                type: fingers_crossed
                excluded_http_codes: [404, 405]
            nested:
                level: debug
                type: stream
                path: php://stderr
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                path: php://stderr
                channels: [deprecation]