monolog:
    handlers:
        main:
            level: error
            type: stream
            channels: ["!event"]
            path: "%kernel.logs_dir%/%kernel.environment%.log"
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
